---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Source databases
[lsb](https://www.leibniz-lsb.de/en/research/technology-facilities/databases) \
[foodb](https://foodb.ca/) \
[AFCD](https://www.foodstandards.gov.au/science-data/monitoringnutrients/afcd/australian-food-composition-database-download-excel-files#nutrient) \ 
[CoFID](https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid)


```{r prep-data, cache=TRUE}
source("R/prep_afcd.R")
source("R/prep_foodb.R")
source("R/prep_cofid.R")
```


```{r compare, echo = FALSE, eval = FALSE}
library(tidyverse)

do.call(
    rbind,
    list(
        afcd_df %>% mutate(db = "AFCD"),
        foodb_df %>% mutate(db = "foodb"),
        cofid_df %>%
            dplyr::select(colnames(afcd_df)) %>%
            mutate(db = "CoFID")
    )
) %>%

    ggplot() +
    aes(x = name, y = value, fill = name) +

    geom_boxplot(aes(group = name)) +
    geom_point(shape = 21) +

    xlab(NULL) +
    ylab(NULL) +

    facet_grid(db ~ Food.Cat, scales = "free_y") +
    theme_bw() +
    theme(
        axis.text.x = element_blank(),
        strip.text.y.right = element_text(angle = 0)
    )

```

```{r plot_cabbages, fig.width=12, fig.height=14}
source("R/cabbage_comparison.R")
cabbage_df %>%
    filter(!is.na(food_1)) %>%

    ggplot() +

    aes(x = food_2, y = name, fill = value) +
    geom_tile() +

    scale_y_discrete(position = "right") +
    scale_fill_gradient2(high = "red", low = "blue", midpoint = 0) +

    xlab(NULL) + 
    ylab(NULL) + 
    facet_wrap(~food_1, scales = "free_x", ncol = 4) +
    theme(axis.text.x = element_text(hjust = 0, angle = 345))

```

```{r pca}
source("R/pca_cabbage_comparison.R")
ggplot(pca) +
    aes(
        x = PC1,
        y = PC2,
        fill = Food,
        shape = Preparation
    ) +

    #Create the points and ellipses
    stat_ellipse(geom = "polygon", alpha = 1 / 4) +
    geom_point(size = 3, col = "black") +

    scale_shape_manual(
        values = c(
            "raw" = 21,
            "boiled with salt" = 22,
            "boiled without salt" = 23
        )
    ) +
    guides(fill = guide_legend(override.aes = list(shape = 21))) +

    theme_bw()

```

